// =========================================================================
// CAMPAIGN LEVELS CONFIGURATION (info.js)
// =========================================================================

const campaignLevels = [
    { level: 1, title: "Tutorial 1: Infantry Advance", blueUnits: [{name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Infantry', type: 'land', range: 2}], customRedPos: [{c: 17, r: 0}] },
    { level: 2, title: "Tutorial 2: Armored Advance", blueUnits: [{name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 17, r: 0}] },
    { level: 3, title: "Tutorial 3: Elimination Protocol", blueUnits: [{name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Infantry', type: 'land', range: 2}], customRedPos: [{c: 4, r: 5}] },
    { level: 4, title: "Tutorial 4: Defensive Line", blueUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Infantry', type: 'land', range: 2}], customRedPos: [{c: 3, r: 4}, {c: 7, r: 1}] },
    { level: 5, title: "Tutorial 5: Armored Defense", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 3, r: 4}, {c: 7, r: 1}] },
    { level: 6, title: "Level 1: Border Skirmish", blueUnits: [{name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Infantry', type: 'land', range: 2}] },
    { level: 7, title: "Level 2: Dual Threat", blueUnits: [{name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Infantry', type: 'land', range: 2}], customRedPos: [{c: 21, r: 4}, {c: 11, r: 2}] },
    { level: 8, title: "Level 3: Armored Advance", blueUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Tank', type: 'land', range: 3}] },
    { level: 9, title: "Level 4: Gold Core Clash", blueUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], customRedPos: [{c: 6, r: 4}, {c: 12, r: 7}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}] },
    { level: 10, title: "Level 5: Gold Core Blitz", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 1, r: 5}, {c: 12, r: 7}], customBluePos: [{c: 0, r: 11}, {c: 5, r: 14}] },
    { level: 11, title: "Level 6: Gold Core Siege", blueUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], customRedPos: [{c: 6, r: 4}, {c: 12, r: 7}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}] },
    { level: 12, title: "Level 7: Tactical Gold Pincer", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 1, r: 5}, {c: 6, r: 4}, {c: 12, r: 7}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 5, r: 14}] },
    { level: 13, title: "Level 8: Iron Core Wall", blueUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 6, r: 4}, {c: 12, r: 7}, {c: 1, r: 5}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}, {c: 5, r: 14}] },
    { level: 14, title: "Level 9: Vanguard Core Breach", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 6, r: 4}, {c: 12, r: 7}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}] },
    { level: 15, title: "Level 10: Combined Gold Ops", blueUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 1, r: 5}, {c: 6, r: 4}, {c: 12, r: 7}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 5, r: 14}] },
    { level: 16, title: "Level 11: Fortress Core Outpost", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 6, r: 4}, {c: 12, r: 7}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}, {c: 5, r: 14}] },
    { level: 17, title: "Level 12: The Core Gauntlet", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 1, r: 5}, {c: 6, r: 4}, {c: 12, r: 7}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}] },
    { level: 18, title: "Level 13: Grand Core Siege", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 6, r: 4}, {c: 12, r: 7}, {c: 1, r: 5}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}] },
    { level: 19, title: "Level 14: Final Core Front", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 1, r: 5}, {c: 6, r: 4}, {c: 12, r: 7}, {c: 16, r: 12}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}] },
    { level: 20, title: "Level 15: Ultimate Judgment Core", blueUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Infantry', type: 'land', range: 2}, {name: 'Tank', type: 'land', range: 3}], redUnits: [{name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}, {name: 'Tank', type: 'land', range: 3}], customRedPos: [{c: 1, r: 5}, {c: 6, r: 4}, {c: 12, r: 7}, {c: 16, r: 12}, {c: 11, r: 2}], customBluePos: [{c: 0, r: 11}, {c: 6, r: 14}, {c: 11, r: 16}, {c: 5, r: 14}] }
];